<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title></title>
    <meta http-equiv="Content-type" content="text-html/ charset=utf-8" />
    
    <link href="/static/ext/resources/css/ext-all.css" media="all" rel="stylesheet" type="text/css" />
    <link href="/static/ext/resources/css/ux-all.css" media="all" rel="stylesheet" type="text/css" />

    <script src="/static/js/init.js" type="text/javascript" charset="utf-8"></script>

    <link href="favicon.ico" rel="shortcut icon"/>
    <link href="/static/favicon.png" type="image/png" rel="shortcut icon"/>

</head>
<body>
   <div class="center-col" tal:content="structure php: this.layout().content" />
</body>
</html>
