create table placeholder111 (a int); -- FIXME
SET @sql = CONCAT('DROP TABLE IF EXISTS', (
        SELECT CONCAT('`_a`, `', GROUP_CONCAT(INFORMATION_SCHEMA.TABLES.TABLE_NAME SEPARATOR '`, `'),'`')
        FROM INFORMATION_SCHEMA.TABLES
        WHERE INFORMATION_SCHEMA.TABLES.TABLE_SCHEMA = DATABASE()
    )
    , ';');
PREPARE DropAllTables FROM @sql;

SET FOREIGN_KEY_CHECKS = 0;
EXECUTE DropAllTables;
SET FOREIGN_KEY_CHECKS = 1;

DEALLOCATE PREPARE DropAllTables;
