CREATE TABLE File ( 
	id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	mimeType VARCHAR(255) NOT NULL,
	size BIGINT UNSIGNED NOT NULL ,
	server INTEGER UNSIGNED NOT NULL DEFAULT 0,
	ownerId INTEGER UNSIGNED NULL,
	accessType INTEGER UNSIGNED NOT NULL DEFAULT 0
)
TYPE=InnoDB;
