CREATE TABLE User (
	id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	username VARCHAR(45) NOT NULL,
	password CHAR(32) NOT NULL,
	countryCode CHAR(2) NOT NULL,
	email VARCHAR(255) NULL,
	role VARCHAR(64) NOT NULL,
	createdAt DATETIME NOT NULL,
	PRIMARY KEY(id),
	UNIQUE KEY(username)
)
TYPE=InnoDB;
	
CREATE TABLE UserSettings (
	id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	userId INT UNSIGNED NOT NULL,
	name VARCHAR(64) NOT NULL,
	value VARCHAR(255) NOT NULL,
	PRIMARY KEY(id)
)
TYPE=InnoDB;
